[package]
name = "j1939-rs"
version = "0.1.0"
edition = "2024"
description = "A Rust library for working with SAE J1939 protocol messages in embedded and automotive systems."
license = "MIT"
readme = "https://github.com/cojmeister/j1939-rs/blob/master/README.md"
homepage = "https://github.com/cojmeister/j1939-rs"
repository = "https://github.com/cojmeister/j1939-rs"
keywords = ["j1939", "can", "automotive", "embedded", "no-std"]
categories = ["aerospace", "aerospace::protocols", "no-std", "no-std::no-alloc", "embedded", "encoding"]

[dependencies]
j1939-core = { path = "../j1939-core" }
j1939-macros = { path = "../j1939-macros" }

[dev-dependencies]
proptest = "1.0"