[package]
name = "j1939-macros"
version = "0.1.2"
edition = "2024"
description = "Macros crate for j1939-rs"
license = "MIT"
homepage = "https://github.com/cojmeister/j1939-rs"
repository = "https://github.com/cojmeister/j1939-rs"
keywords = ["j1939", "can", "automotive", "embedded", "no-std"]
categories = ["aerospace::protocols", "no-std::no-alloc", "embedded", "encoding"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
tabled = "0.20.0"

[dev-dependencies]
trybuild = "1.0"