[package]
name = "j1939-core"
version = "0.1.0"
edition = "2024"
description = "Core crate for j1939-rs"
license = "MIT"
homepage = "https://github.com/cojmeister/j1939-rs"
repository = "https://github.com/cojmeister/j1939-rs"
keywords = ["j1939", "can", "automotive", "embedded", "no-std"]
categories = ["aerospace", "aerospace::protocols", "no-std", "no-std::no-alloc", "embedded", "encoding"]


[dependencies]

[dev-dependencies]
proptest = "1.0"